version: '3.8'

services:
  chatapp:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - chatapp-network

  # Optional: Add Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - chatapp
    networks:
      - chatapp-network
    restart: unless-stopped

networks:
  chatapp-network:
    driver: bridge

volumes:
  logs: